// priceList.js - Full product price list

const priceList = [
    { code: "BATHMATREC", description: "Rectangular Bathmat", price: 17.34 },
    { code: "MATTOI", description: "Toilet Mat", price: 20.00 },
    { code: "MATTSC", description: "Toilet Seat Cover", price: 20.00 },
    { code: "BASE", description: "Base cover", price: 15.00 },
    { code: "TWLHAND", description: "Hand Towel", price: 14.70 },
    { code: "BATHTWL", description: "Bath Towel", price: 18.00 },
    { code: "BATHSH", description: "Bath Sheet", price: 21.00 },
    { code: "BATHMA", description: "Bath Math", price: 18.84 },
    { code: "BLANKK", description: "King Blanket", price: 121.26 },
    { code: "BLANKQ", description: "Queen Blanket", price: 121.26 },
    { code: "BLANKDBL", description: "Double Blanket", price: 65.54 },
    { code: "COMFKS", description: "King Comforter", price: 114.34 },
    { code: "COMFQUE", description: "Queen Comforter", price: 114.34 },
    { code: "COMFDBL", description: "Double Comforter", price: 114.34 },
    { code: "COMFSI", description: "Single Comforter", price: 56.34 },
    { code: "CURTDRP", description: "Curtains (Per Drop)", price: 103.90 },
    { code: "DISCLT", description: "Dish Cloth", price: 5.00 },
    { code: "PILLCASE", description: "Pillowcase", price: 8.50 },
    { code: "LFRAGS", description: "Large Floor Rags", price: 60.00 },
    { code: "MFRAGS", description: "Medium Floor Rags", price: 55.00 },
    { code: "SFRAGS", description: "Small Floor Rags", price: 50.00 },
    { code: "BDFR", description: "Bed Frill", price: 30.52 },
    { code: "BEATWL", description: "Beach Towel", price: 10.42 },
    { code: "CARSML", description: "Small Carpet", price: 50.00 },
    { code: "CARMED", description: "Medium Carpet", price: 55.00 },
    { code: "CARLRG", description: "Large Carpet", price: 60.00 },
    { code: "BEDMAT", description: "Bedside Mat", price: 69.30 },
    { code: "BLANKS", description: "Single Blanket", price: 60.00 },
    { code: "BSQ", description: "Bed Spread-Quilt", price: 121.26 },
    { code: "SWBS", description: "Swabs", price: 5.00 },
    { code: "CCOVLRG", description: "Cushion Covers/Large", price: 43.29 },
    { code: "LACECURT", description: "Small Lace Cutain", price: 60.00 },
    { code: "CCOVSML", description: "Cushion Cover-Small", price: 38.10 },
    { code: "CONTPCASE", description: "Continental Pillowcase", price: 10.00 },
    { code: "CONTPLW", description: "Continental Pillow", price: 86.58 },
    { code: "COUSCOVLRG", description: "Large Cushion Cover", price: 43.29 },
    { code: "COUSCOVMED", description: "Medium Cushion Cover", price: 26.01 },
    { code: "COUSCOVS", description: "Small Cushion Covers", price: 20.84 },
    { code: "DBLDUVFEA", description: "Duvet Double Feather", price: 112.59 },
    { code: "DBLTHW", description: "Double Throw", price: 95.25 },
    { code: "DELCOL", description: "Delivery/Collection Fee", price: 0.00 },
    { code: "DUVCOVKS", description: "King-size Duvet Cover", price: 23.21 },
    { code: "DUVCOVQU", description: "Queen Duvet Cover", price: 16.42 },
    { code: "DUVCOVDO", description: "Double Duvet Cover", price: 15.00 },
    { code: "DUVCOV3/4", description: "3/4 Duvet Cover", price: 16.42 },
    { code: "DUVCOVSI", description: "Single Duvet Cover", price: 13.50 },
    { code: "DUVDBLINN", description: "Double Duvet Inner", price: 103.90 },
    { code: "FACCLTH", description: "Face Cloth", price: 2.82 },
    { code: "FREJAC", description: "Freezer Jackets", price: 83.80 },
    { code: "GLASCLO", description: "Glass Cloth", price: 6.12 },
    { code: "GOWN/W/B", description: "Gowns with Belt", price: 28.90 },
    { code: "KSDUVINN/F", description: "King Duvet Inner-Feather", price: 129.86 },
    { code: "KSDUVINN/N", description: "King Duvet Inner-Normal", price: 95.25 },
    { code: "KSFITSHT", description: "King Fitted Sheet", price: 20.64 },
    { code: "KSFLATSHT", description: "King Flat Sheet", price: 20.64 },
    { code: "KSMATPRO", description: "King Mattress Protector", price: 60.63 },
    { code: "KSQUIL", description: "King Quilt", price: 147.21 },
    { code: "POOLCUS", description: "Pool Cushion Cover", price: 40.00 },
    { code: "MATCOV", description: "Mattress Cover", price: 22.38 },
    { code: "MATLRG", description: "Large Rectangular Mat", price: 34.68 },
    { code: "MATPRO/K/Q", description: "Mattress Protector (K/Q)", price: 60.63 },
    { code: "MATPRODO", description: "Double Mattress Protector", price: 51.96 },
    { code: "MATPRO3/4", description: "Mattress Protector (3/4)", price: 20.00 },
    { code: "MATPROS", description: "Mattress Protector (Single)", price: 43.29 },
    { code: "MATREC", description: "Rectangular Mats", price: 17.34 },
    { code: "MATUSHP", description: "U Shaped Toilet Mat", price: 6.92 },
    { code: "NAPCLOTH", description: "Napkin Cloth", price: 2.62 },
    { code: "NGTFRILKS", description: "Night Frill King", price: 65.00 },
    { code: "NGTFRILQS", description: "Night Frill Queen", price: 60.00 },
    { code: "NGTFRILDO", description: "Night Frill Double", price: 21.49 },
    { code: "NGTFRIL3/4", description: "Night Frill 3/4", price: 19.49 },
    { code: "NGTFRILSI", description: "Night Frill Single", price: 19.49 },
    { code: "OVENGLO", description: "Oven Gloves", price: 17.34 },
    { code: "PILLPRO", description: "Continental Pillow Protector", price: 26.01 },
    { code: "PILLPROSTD", description: "Standard Pillow Protector", price: 8.67 },
    { code: "PILLSTD", description: "Standard Pillow", price: 81.94 },
    { code: "PLCEMAT", description: "Place Mats", price: 5.78 },
    { code: "PLWCASLRG", description: "Large Pillowcases", price: 11.29 },
    { code: "QSFITSHT", description: "Queen Fitted Sheet", price: 17.09 },
    { code: "DOFITSHT", description: "Double Fitted Sheet", price: 15.00 },
    { code: "DOFLASHT", description: "Double Flat Sheet", price: 15.00 },
    { code: "SIFITSHT", description: "Single Fitted Sheet", price: 14.50 },
    { code: "3/4FITSHT", description: "3/4 Fitted Sheet", price: 11.50 },
    { code: "SIFLASHT", description: "Single Flat Sheet", price: 14.50 },
    { code: "QSFLATSHT", description: "Queen Flat Sheet", price: 17.09 },
    { code: "RWASH", description: "Re-Wash", price: 0.00 },
    { code: "RUGLRG", description: "Large size rug", price: 60.00 },
    { code: "RUGSML", description: "Small size rug", price: 30.00 },
    { code: "RUGSTD", description: "Standard size rug", price: 35.00 },
    { code: "SHOWCURT", description: "Shower Curtain", price: 38.10 },
    { code: "SINGDUVINN", description: "Single Duvet Inner", price: 85.77 },
    { code: "SINGLETHRW", description: "Single Throw", price: 57.13 },
    { code: "STAINTRT", description: "Stain Treatment", price: 0.00 },
    { code: "TBLCLOTH", description: "Tablecloth", price: 17.34 },
    { code: "TBLRUN", description: "Table Runner", price: 17.34 },
    { code: "THROW/A/S", description: "Throws-All Sizes", price: 86.58 },
    { code: "TURNMAT", description: "Turndown Mats", price: 4.71 },
    { code: "TWLTEA", description: "Tea Towel", price: 4.77 }
];
